repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system

  - repo: https://github.com/pytest-dev/pytest
    rev: 8.1.1
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
